# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: true

# Site meta
title: Swadeshi Hub
tagline: ''
description: 'A Hub of Swadeshi - Made in India Products.Find Out : Lets you distinguish Swadeshi Products from Videshi. Made in India : Top Made in India brands that are most trusted by millions of citizens across the country are curated right here. Vocal for Local : This is our very own unique initiative to curate and support all the local firms and businesses. A list of all local businesses producing native products will be selected and displayed.'
keywords: 'swadeshi, made in india, india, local, service'
url: https://swadeshihub.github.io
baseurl: /
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Swadeshi Hub
  bio: A Hub of Swadeshi - Made in India Products
  image: author
  url: 
  email: swadeshihub.info@gmail.com
  twitter: HubSwadeshi

social:
  twitter: https://twitter.com/HubSwadeshi

version: 2.0.0

# github:
#   repo: https://github.com/

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

google_analytics_key: UA-172912914-1
google-site-verification: 3DscbxAkFyePxX8tydaYU82Bxkg-8mmEuHfNhQJgL8o

# Content
excerpt_separator: <!-- Read more -->

navigation:
  Vocal for Local: /vocal-for-local
  About Us: /about
  Contact: /contact

collections:
  categories:
    output: true
  vocalforlocal:
    output: true
  madeinindia:
    output: true
  service:
    output: true
  simple:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: categories
    values:
      layout: categories
      lang: en
      permalink: /:title/
  - scope:
      path: ''
      type: madeinindia
    values:
      layout: madeinindia
      lang: en
      permalink: /:title/
  - scope:
      path: ''
      type: vocalforlocal
    values:
      layout: vocalforlocal
      lang: en
      permalink: /:title/
  - scope:
      path: ''
      type: service
    values:
      layout: service
      lang: en
      permalink: /:title/
  - scope:
      path: ''
      type: simple
    values:
      layout: simple
      lang: en
      permalink: /:title/