# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: true

# Site meta
title: Swadeshi Hub
tagline: 'Vocal for Local'
description: 'A Hub of Swadeshi - Made in India Products'
keywords: 'swadeshi, made in india, india'
url: https://swadeshihub.github.io
baseurl: /
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Swadeshi Hub
  bio: A Hub of Swadeshi - Made in India Products
  image: author
  url: 
  email: 
#   twitter: 

# social:
#   twitter: https://twitter.com/connor_baer
#   instagram: https://instagram.com/connor_baer
#   github: https://github.com/connor-baer/summer

version: 2.0.0

# github:
#   repo: https://github.com/connor-baer/summer

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
#   GitHub: https://github.com/swadeshi-hub
#   Download: https://github.com/connor-baer/summer/archive/gh-pages.zip

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
